site_name: Sierra Express
site_url: https://sjohnsonaz.github.io/sierra-express
repo_url: https://github.com/sjohnsonaz/sierra-express
copyright: Copyright &copy; 2017 Sean Johnson
pages:
    - Home: index.md
theme: readthedocs